export const students = [
    {
        id: 's1',
        name: 'Alex Johnson',
        email: 'alex.j@college.edu',
        batch: '2025-CS-A',
        placementReadiness: 82,
        platforms: {
            leetcode: {
                username: 'alexj',
                solved: 312,
                rating: 1842,
                streak: 14,
                hardSolved: 48,
                mediumSolved: 164,
                easySolved: 100,
            },
            github: {
                username: 'alex-johnson',
                totalCommits: 847,
                publicRepos: 18,
                stars: 34,
            },
            codeforces: {
                username: 'alexj_cf',
                totalSolved: 198,
                rating: 1654,
                maxRating: 1720,
            },
            codechef: {
                username: 'alexj_cc',
                solved: 95,
                rating: 1780,
            },
            hackerrank: {
                username: 'alexj_hr',
                solved: 60,
                stars: 4,
            },
        },
        topicStats: [
            { topic: 'Arrays', solved: 85 },
            { topic: 'DP', solved: 42 },
            { topic: 'Graphs', solved: 35 },
            { topic: 'Trees', solved: 60 },
            { topic: 'Strings', solved: 50 },
            { topic: 'Math', solved: 40 },
        ],
        contestHistory: [
            { date: '2024-08-01', rating: 1620 },
            { date: '2024-09-01', rating: 1680 },
            { date: '2024-10-01', rating: 1705 },
            { date: '2024-11-01', rating: 1760 },
            { date: '2024-12-01', rating: 1800 },
            { date: '2025-01-01', rating: 1842 },
        ],
        aiSuggestions: [
            {
                topic: 'Dynamic Programming',
                tip: 'Your DP solve rate is below average. Focus on classic patterns like knapsack, LCS, and coin change to boost your score significantly.',
                problems: [
                    'LeetCode #322 – Coin Change',
                    'LeetCode #300 – Longest Increasing Subsequence',
                    'LeetCode #416 – Partition Equal Subset Sum',
                ],
            },
            {
                topic: 'Graph Algorithms',
                tip: 'You have solved fewer graph problems compared to your peers. Start with BFS/DFS fundamentals, then move to shortest path algorithms.',
                problems: [
                    'LeetCode #200 – Number of Islands',
                    'LeetCode #743 – Network Delay Time',
                    'LeetCode #207 – Course Schedule',
                ],
            },
            {
                topic: 'Binary Search',
                tip: 'Practice applying binary search on answers, not just sorted arrays. This unlocks a powerful class of medium/hard problems.',
                problems: [
                    'LeetCode #153 – Find Minimum in Rotated Sorted Array',
                    'LeetCode #875 – Koko Eating Bananas',
                    'LeetCode #1011 – Capacity to Ship Packages',
                ],
            },
        ],
    },

    {
        id: 's2',
        name: 'Priya Mehta',
        email: 'priya.m@college.edu',
        batch: '2025-CS-A',
        placementReadiness: 91,
        platforms: {
            leetcode: {
                username: 'priyam',
                solved: 430,
                rating: 2105,
                streak: 30,
                hardSolved: 92,
                mediumSolved: 210,
                easySolved: 128,
            },
            github: {
                username: 'priya-mehta',
                totalCommits: 1240,
                publicRepos: 27,
                stars: 88,
            },
            codeforces: {
                username: 'priyam_cf',
                totalSolved: 310,
                rating: 1950,
                maxRating: 2010,
            },
            codechef: {
                username: 'priyam_cc',
                solved: 140,
                rating: 2050,
            },
            hackerrank: {
                username: 'priyam_hr',
                solved: 90,
                stars: 5,
            },
        },
        topicStats: [
            { topic: 'Arrays', solved: 120 },
            { topic: 'DP', solved: 95 },
            { topic: 'Graphs', solved: 80 },
            { topic: 'Trees', solved: 100 },
            { topic: 'Strings', solved: 75 },
            { topic: 'Math', solved: 60 },
        ],
        contestHistory: [
            { date: '2024-08-01', rating: 1820 },
            { date: '2024-09-01', rating: 1890 },
            { date: '2024-10-01', rating: 1940 },
            { date: '2024-11-01', rating: 2000 },
            { date: '2024-12-01', rating: 2060 },
            { date: '2025-01-01', rating: 2105 },
        ],
        aiSuggestions: [
            {
                topic: 'Advanced DP',
                tip: 'Level up with bitmask DP and interval DP to tackle competitive programming hard problems.',
                problems: [
                    'LeetCode #1335 – Minimum Difficulty of a Job Schedule',
                    'LeetCode #664 – Strange Printer',
                    'LeetCode #1000 – Minimum Cost to Merge Stones',
                ],
            },
        ],
    },

    {
        id: 's3',
        name: 'Rahul Sharma',
        email: 'rahul.s@college.edu',
        batch: '2025-CS-A',
        placementReadiness: 74,
        platforms: {
            leetcode: {
                username: 'rahuls',
                solved: 220,
                rating: 1590,
                streak: 5,
                hardSolved: 22,
                mediumSolved: 110,
                easySolved: 88,
            },
            github: {
                username: 'rahul-sharma',
                totalCommits: 430,
                publicRepos: 10,
                stars: 12,
            },
            codeforces: {
                username: 'rahuls_cf',
                totalSolved: 145,
                rating: 1420,
                maxRating: 1500,
            },
            codechef: {
                username: 'rahuls_cc',
                solved: 70,
                rating: 1560,
            },
            hackerrank: {
                username: 'rahuls_hr',
                solved: 40,
                stars: 3,
            },
        },
        topicStats: [
            { topic: 'Arrays', solved: 65 },
            { topic: 'DP', solved: 28 },
            { topic: 'Graphs', solved: 20 },
            { topic: 'Trees', solved: 40 },
            { topic: 'Strings', solved: 35 },
            { topic: 'Math', solved: 32 },
        ],
        contestHistory: [
            { date: '2024-08-01', rating: 1350 },
            { date: '2024-09-01', rating: 1400 },
            { date: '2024-10-01', rating: 1450 },
            { date: '2024-11-01', rating: 1520 },
            { date: '2024-12-01', rating: 1570 },
            { date: '2025-01-01', rating: 1590 },
        ],
        aiSuggestions: [
            {
                topic: 'Sliding Window',
                tip: 'Master the sliding window pattern — it covers a wide range of medium problems that commonly appear in interviews.',
                problems: [
                    'LeetCode #3 – Longest Substring Without Repeating Characters',
                    'LeetCode #76 – Minimum Window Substring',
                    'LeetCode #567 – Permutation in String',
                ],
            },
        ],
    },

    {
        id: 's4',
        name: 'Ananya Patel',
        email: 'ananya.p@college.edu',
        batch: '2025-CS-A',
        placementReadiness: 55,
        platforms: {
            leetcode: {
                username: 'ananyap',
                solved: 98,
                rating: 1280,
                streak: 2,
                hardSolved: 5,
                mediumSolved: 40,
                easySolved: 53,
            },
            github: {
                username: 'ananya-patel',
                totalCommits: 180,
                publicRepos: 5,
                stars: 4,
            },
            codeforces: {
                username: 'ananyap_cf',
                totalSolved: 55,
                rating: 1100,
                maxRating: 1150,
            },
            codechef: {
                username: 'ananyap_cc',
                solved: 30,
                rating: 1250,
            },
            hackerrank: {
                username: 'ananyap_hr',
                solved: 20,
                stars: 2,
            },
        },
        topicStats: [
            { topic: 'Arrays', solved: 35 },
            { topic: 'DP', solved: 8 },
            { topic: 'Graphs', solved: 5 },
            { topic: 'Trees', solved: 18 },
            { topic: 'Strings', solved: 20 },
            { topic: 'Math', solved: 12 },
        ],
        contestHistory: [
            { date: '2024-08-01', rating: 1050 },
            { date: '2024-09-01', rating: 1100 },
            { date: '2024-10-01', rating: 1150 },
            { date: '2024-11-01', rating: 1200 },
            { date: '2024-12-01', rating: 1240 },
            { date: '2025-01-01', rating: 1280 },
        ],
        aiSuggestions: [
            {
                topic: 'Arrays & Hashing',
                tip: 'Build a strong foundation with arrays and hash maps. These are the most frequently tested topics in entry-level interviews.',
                problems: [
                    'LeetCode #1  – Two Sum',
                    'LeetCode #217 – Contains Duplicate',
                    'LeetCode #49  – Group Anagrams',
                ],
            },
        ],
    },

    {
        id: 's5',
        name: 'Vikram Singh',
        email: 'vikram.s@college.edu',
        batch: '2025-CS-B',
        placementReadiness: 68,
        platforms: {
            leetcode: {
                username: 'vikrams',
                solved: 175,
                rating: 1480,
                streak: 7,
                hardSolved: 14,
                mediumSolved: 90,
                easySolved: 71,
            },
            github: {
                username: 'vikram-singh',
                totalCommits: 320,
                publicRepos: 8,
                stars: 9,
            },
            codeforces: {
                username: 'vikrams_cf',
                totalSolved: 110,
                rating: 1310,
                maxRating: 1380,
            },
            codechef: {
                username: 'vikrams_cc',
                solved: 55,
                rating: 1440,
            },
            hackerrank: {
                username: 'vikrams_hr',
                solved: 35,
                stars: 3,
            },
        },
        topicStats: [
            { topic: 'Arrays', solved: 55 },
            { topic: 'DP', solved: 20 },
            { topic: 'Graphs', solved: 18 },
            { topic: 'Trees', solved: 30 },
            { topic: 'Strings', solved: 28 },
            { topic: 'Math', solved: 24 },
        ],
        contestHistory: [
            { date: '2024-08-01', rating: 1250 },
            { date: '2024-09-01', rating: 1310 },
            { date: '2024-10-01', rating: 1360 },
            { date: '2024-11-01', rating: 1400 },
            { date: '2024-12-01', rating: 1450 },
            { date: '2025-01-01', rating: 1480 },
        ],
        aiSuggestions: [
            {
                topic: 'Recursion & Backtracking',
                tip: 'Strengthen your recursion skills before moving to DP. Many DP problems are simply memoized recursion.',
                problems: [
                    'LeetCode #78  – Subsets',
                    'LeetCode #46  – Permutations',
                    'LeetCode #131 – Palindrome Partitioning',
                ],
            },
        ],
    },
];
